resources:
  - name: app-repo
    type: git
    source:
      uri: https://github.com/savaseeratesli/PipelineExamples.git
      branch: main

  - name: simple-image
    type: docker-image
    source:
      repository: savaseeratesli/simple-image
      tag: latest
      username: ((dockerhub_username))
      password: ((dockerhub_password))

jobs:
  - name: deploy-to-kubernetes
    plan:
      - get: app-repo
        trigger: true

      - get: simple-image
        trigger: true

      - task: deploy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: bitnami/kubectl
              tag: latest
          inputs:
            - name: app-repo
          params:
            KUBE_CONFIG_B64: ((kubeconfig))
          run:
            path: sh
            args:
              - -exc
              - |
                echo "Deploying to Kubernetes..."

                export HOME=/tmp
                mkdir -p $HOME/.kube

                echo "$KUBE_CONFIG_B64" | base64 -d > $HOME/.kube/config
                chmod 600 $HOME/.kube/config

                echo "Cluster kontrol:"
                kubectl get nodes

                echo "Manifestler uygulanıyor..."
                kubectl apply -f app-repo/deployment.yml
                kubectl apply -f app-repo/service.yml
                kubectl apply -f app-repo/hpa.yml

                echo "Deployment restart..."
                DEPLOYMENT_NAME=$(kubectl get deploy -o jsonpath='{.items[0].metadata.name}')
                kubectl rollout restart deployment $DEPLOYMENT_NAME

                echo "Rollout bekleniyor..."
                kubectl rollout status deployment/$DEPLOYMENT_NAME --timeout=360s

                echo "Deploy tamamlandı!"
