resources:
  # Git repo (senin PipelineExamples projen)
  - name: pipelineexamples
    type: git
    icon: github
    source:
      uri: https://github.com/savaseeratesli/PipelineExamples.git
      branch: main

  # Docker imajını push edeceğin hedef (Docker Hub)
  - name: simple-image
    type: registry-image
    icon: docker
    source:
      repository: savaseeratesli/simple-image
      tag: latest

jobs:
  - name: build-and-push
    plan:
      - get: pipelineexamples
        trigger: true

      # Docker imajını build et
      - task: build-dotnet-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: pipelineexamples
          outputs:
            - name: image
          params:
            CONTEXT: pipelineexamples
            DOCKERFILE: pipelineexamples/Dockerfile
          run:
            path: build

      # Docker imajını push et
      - put: simple-image
        params:
          image: image/image.tar
