resources:
- name: repo
  type: git
  source:
    uri: "https://github.com/savaseeratesli/PipelineExamples.git" 
    branch: main

- name: image
  type: docker-image
  source:
    repository: "savaseeratesli/k8salistirmalari" 
    username: ((dockerhub_username)) # Concourse varları
    password: ((dockerhub_password))

jobs:
- name: build-and-push
  public: true
  plan:
  - get: repo
    trigger: true
  - task: build-and-publish
    privileged: true     # docker build/push için (concourse-worker config gerektirir)
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine
      inputs:
      - name: repo
      outputs:
      - name: image_output
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          apk add --no-cache docker-cli build-base bash
          cd repo

          # Build docker image
          docker build -t ${IMAGE_REPO}:${BUILD_ID:-latest} .

          # Tag for latest
          docker tag ${IMAGE_REPO}:${BUILD_ID:-latest} ${IMAGE_REPO}:latest

          # Login and push
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push ${IMAGE_REPO}:${BUILD_ID:-latest}
          docker push ${IMAGE_REPO}:latest

    params:
      IMAGE_REPO: ((image.repository)) # from resource
      DOCKER_USERNAME: ((dockerhub_username)) # pipeline vars
      DOCKER_PASSWORD: ((dockerhub_password))
