resources:
- name: app-repo
  type: git
  source:
    uri: https://github.com/savaseeratesli/PipelineExamples.git
    branch: main

jobs:
  - name: build-and-push
    plan:
      - get: app-repo
        trigger: true
      - put: simple-image
        params:
          build: app-repo

  - name: deploy-to-kubernetes
    plan:
      - get: app-repo
        passed: [build-and-push]
      - get: simple-image
        passed: [build-and-push]
        trigger: true   # 🔥 buraya dikkat

      - task: deploy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: bitnami/kubectl
              tag: latest
          inputs:
            - name: app-repo
          params:
            KUBE_CONFIG: ((kubeconfig))
          run:
            path: sh
            args:
              - -exc
              - |
                echo "🚀 Deploying to Kubernetes..."

                mkdir -p ~/.kube
                echo "$KUBE_CONFIG" > ~/.kube/config

                echo "🔍 Applying Deployment, Service and HPA..."
                kubectl apply -f app-repo/deployment.yml
                kubectl apply -f app-repo/service.yml
                kubectl apply -f app-repo/hpa.yml

                echo "♻️ Restarting deployment to pull latest image..."
                kubectl rollout restart deployment/hello-world

                echo "⏳ Waiting for rollout to complete..."
                kubectl rollout status deployment/hello-world

                echo "✅ Deployment completed!"
