resources:
  # --- 1. Kaynak kod deposu (GitHub) ---
  - name: app-repo
    type: git
    source:
      uri: https://github.com/savaseeratesli/PipelineExamples.git
      branch: main

  # --- 2. Docker image kaynağı ---
  - name: simple-image
    type: docker-image
    source:
      repository: savaseeratesli/simple-image
      username: ((dockerhub_username))
      password: ((dockerhub_password))

jobs:
  # --- JOB 1: Docker image build + push ---
  - name: build-and-push
    plan:
      - get: app-repo
        trigger: true

      - task: create-tag
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          inputs:
            - name: app-repo
          outputs:
            - name: version
          run:
            path: sh
            args:
              - -exc
              - |
                TAG="build-$(date +'%Y%m%d-%H%M%S')"
                echo $TAG > version/tag.txt
                echo "Generated image tag: $TAG"

      - put: simple-image
        params:
          build: app-repo
          tag_file: version/tag.txt       # ÖNEMLİ: Bu satır build imajına unique tag verir
          additional_tags: latest         # latest ek olarak güncellenir

  # --- JOB 2: Kubernetes'e deploy et ---
  - name: deploy-to-kubernetes
    plan:
      - get: app-repo
        passed: [build-and-push]
        trigger: true
      - get: simple-image
        passed: [build-and-push]
      - get: version
        passed: [build-and-push]

      - task: deploy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: bitnami/kubectl
              tag: latest
          inputs:
            - name: app-repo
            - name: version
          params:
            KUBE_CONFIG: ((kubeconfig))
          run:
            path: sh
            args:
              - -exc
              - |
                echo "Deploying to Kubernetes..."
                mkdir -p ~/.kube
                echo "$KUBE_CONFIG" > ~/.kube/config

                TAG=$(cat version/tag.txt)
                echo "Using image tag: $TAG"

                DEPLOYMENT_FILE="app-repo/deployment.yml"

                # Deployment içindeki image tag'ını yeni tag ile değiştir
                sed -i "s|\(image: savaseeratesli/simple-image:\).*|\1$TAG|g" $DEPLOYMENT_FILE

                echo "Applying manifests..."
                kubectl apply -f $DEPLOYMENT_FILE
                kubectl apply -f app-repo/service.yml
                kubectl apply -f app-repo/hpa.yml

                echo "Restarting deployment..."
                DEPLOYMENT_NAME=$(kubectl get deploy -o jsonpath='{.items[0].metadata.name}')
                kubectl rollout restart deployment $DEPLOYMENT_NAME

                echo "Waiting for rollout..."
                kubectl rollout status deployment/$DEPLOYMENT_NAME --timeout=360s

                echo "Deployment completed successfully with image tag: $TAG"
