resources:
  # --- 1. GitHub repository ---
  - name: app-repo
    type: git
    source:
      uri: https://github.com/savaseeratesli/PipelineExamples.git
      branch: main

  # --- 2. Docker image ---
  - name: simple-image
    type: docker-image
    source:
      repository: savaseeratesli/simple-image
      tag: latest
      username: ((dockerhub_username))
      password: ((dockerhub_password))

jobs:
  # --- JOB 1: Docker image build + push ---
  - name: build-and-push
    plan:
      - get: app-repo
        trigger: true
      - put: simple-image
        params:
          build: app-repo

  # --- JOB 2: Kubernetes deploy ---
  - name: deploy-to-kubernetes
    plan:
      - get: app-repo
        trigger: true
        passed: [build-and-push]
      - task: deploy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: bitnami/kubectl
              tag: latest
          inputs:
            - name: app-repo
          params:
            KUBE_CONFIG: ((kubeconfig))
          run:
            path: sh
            args:
              - -exc
              - |
                mkdir -p ~/.kube
                echo "$KUBE_CONFIG" > ~/.kube/config
                echo "🔹 Deploying to Kubernetes..."
                kubectl apply -f deployment.yml
                kubectl apply -f service.yml
                kubectl apply -f hpa.yml
                echo "✅ Deployment complete!"
