resources:
  - name: app-repo
    type: git
    source:
      uri: https://github.com/savaseeratesli/PipelineExamples.git
      branch: main

  - name: simple-image
    type: docker-image
    source:
      repository: savaseeratesli/simple-image
      tag: latest
      username: ((dockerhub_username))
      password: ((dockerhub_password))

jobs:
  - name: build-and-push
    plan:
      - get: app-repo
        trigger: true

      - task: generate-tag
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          outputs:
            - name: tag-info
          run:
            path: sh
            args:
              - -exc
              - |
                TAG=$(date +%Y%m%d-%H%M%S)
                echo $TAG > tag-info/tag.txt
                echo "Tag oluşturuldu: $TAG"

      - put: simple-image
        params:
          build: app-repo
          additional_tags: tag-info/tag.txt
