resources:
  # --- 1. Kaynak kod deposu (GitHub) ---
  - name: app-repo
    type: git
    source:
      uri: https://github.com/savaseeratesli/PipelineExamples.git
      branch: main

  # --- 2. Docker image kaynağı ---
  - name: simple-image
    type: docker-image
    source:
      repository: savaseeratesli/simple-image
      tag: latest
      username: ((dockerhub_username))
      password: ((dockerhub_password))

jobs:
  # --- JOB 1: Docker image build + push ---
  - name: build-and-push
    plan:
      - get: app-repo
        trigger: true
      - put: simple-image
        params:
          build: app-repo   # app-repo dizinindeki Dockerfile kullanılacak
